services:
  proof-server:
    image: 'midnightntwrk/proof-server'
    container_name: "proof-server_$TESTCONTAINERS_UID"
    ports:
      - "0:6300"
    environment:
      EXTRA_ARGS: -v
      RUST_BACKTRACE: "full"
